---

data_dir: 'data/'
figure_dir: 'figures/'
output_dir: 'results/'

seed: 42

nA: 2
nB: 2
nY: 1

max_epochs: 2000
log_epochs: 100


logger:
    version: 1
    formatters:
        default:
            format: '%(asctime)s - %(module)s - %(levelname)s - %(message)s'
    handlers:
        stream_handler:
            class: logging.StreamHandler
            level: DEBUG
            formatter: default
            stream: ext://sys.stdout
        file_handler:
            class: logging.handlers.RotatingFileHandler
            level: DEBUG
            formatter: default
            filename: log.log
            maxBytes: 10485760  # 10MB
            backupCount: 5
            encoding: utf-8
    root:
        level: DEBUG
        handlers:
        - stream_handler
        - file_handler



# 下面的部分目前没有使用
model:
    type: CompetitiveNetwork
    args:
        reparameterize: 'square'


data_loader:
    type: DataLoader
    args:
        batch_size: 9
        shuffle: False

optimizer:
    type: SGD
    args:
        lr: 1e-1
        momentum: 0.9
        weight_decay: 0
loss:
    type: MSELoss()




...