---
data_dir: 'data'
figure_dir: 'figures'
output_dir: 'results/temp'
log_dir: 'logs'

seed: 0

nA: 2
nB: 2
nY: 1

max_epochs: 2000
log_epochs: 100
tol: 1.0e-4

model:
  type: CompetitiveNetwork
  args:
    reparam: square
    mode: notfix

logger:
  version: 1
  formatters:
    default:
      format: '%(asctime)s - %(levelname)s - %(message)s'
  handlers:
    stream_handler:
      class: logging.StreamHandler
      level: INFO
      formatter: default
      stream: ext://sys.stdout
    file_handler:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: default
      filename: test.log
      maxBytes: 10485760 # 10MB
      backupCount: 5
      encoding: utf-8
  root:
    level: DEBUG
    handlers:
      - stream_handler
      - file_handler

# following not used


data_loader:
  type: DataLoader
  args:
    batch_size: 9
    shuffle: False

optimizer:
  type: SGD
  args:
    lr: 1.0e-1
    momentum: 0.9
    weight_decay: 0
loss:
  type: MSELoss()
